import 'dart:ui';

import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';
import 'package:google_fonts/google_fonts.dart';

import '../../data/globals.dart';
import '../../widgets/text.dart';

class termsConditions extends StatefulWidget {
  const termsConditions({super.key});

  @override
  State<termsConditions> createState() => _termsConditionsState();
}

class _termsConditionsState extends State<termsConditions> {
  var h, w;

  @override
  Widget build(BuildContext context) {
    h = MediaQuery.of(context).size.height;
    w = MediaQuery.of(context).size.width;

    return SafeArea(
      child: Scaffold(
        backgroundColor: kHomeBG,
        appBar: PreferredSize(
          child: Container(
            child: ClipRRect(
              child: BackdropFilter(
                filter: ImageFilter.blur(sigmaX: 10, sigmaY: 10),
                child: Container(
                  width: w,
                  height: h * 0.1,
                  decoration: BoxDecoration(color: kDarkBlue3, boxShadow: [
                    BoxShadow(color: kBlack, blurRadius: 20, spreadRadius: -17)
                  ]),
                  alignment: Alignment.center,
                  child: Row(
                    mainAxisAlignment: MainAxisAlignment.start,
                    children: [
                      Padding(
                        padding: EdgeInsets.only(left: 20),
                        child: InkWell(
                            onTap: () {
                              Navigator.pop(context);
                            },
                            child: FaIcon(
                              FontAwesomeIcons.arrowLeft,
                              color: kWhite,
                            )),
                      ),
                      Padding(
                        padding: const EdgeInsets.only(left: 20),
                        child: textWidget(
                            msg: "Terms & Conditions",
                            txtColor: kWhite,
                            txtFontWeight: FontWeight.w600,
                            txtFontSize: h * 0.025),
                      ),
                    ],
                  ),
                ),
              ),
            ),
          ),
          preferredSize: Size(w, h * 0.065),
        ),
        body: SingleChildScrollView(
          physics: BouncingScrollPhysics(),
          child: Column(
            children: [
              SizedBox(height: h * 0.02,),
              Row(
                children: [
                  SizedBox(
                    width: w * 0.03,
                  ),
                  Flexible(
                    child:
                        Text('''TERMS AND CONDITIONS – ATS PHARMACIES LIMITED

 

This document (“Terms and conditions”) is an electronic record in terms of the Information Technology Act, 2000, and rules thereunder, as applicable, and the amended provisions pertaining to electronic records in various statutes, as amended from time to time by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.

 

This document is published in accordance with the provisions of Rule 3(1) of the Information Technology (Intermediaries Guidelines and Digital Media Ethics Code) Rules, 2021 as amended from time to time, which requires publishing of the rules and regulations, privacy policy and Terms for access or usage of https://www.apollopharmacy.in/ website and mobile application.

 

We, at ATS Pharmacies Limited (“APL”, “we,” “us”) provide services to all individuals accessing or using our retail stores or APL platform (“APL Platform ”) for any reason (“you”, “yours”, “User”) subject to the notices, terms, and conditions set forth in these terms and conditions (“Terms and Conditions”, “Agreement”), read with the Privacy Policy. The APL Platform is owned and operated by APL, a company duly incorporated under the provisions of the Companies Act, 2013. By accessing or browsing of the APL Platform and using the Services (as defined below) you indicate your agreement to all the terms and conditions in this Agreement. If you disagree with any part of the Terms and Conditions, then you may discontinue access or use of the APL Platform.

 

1.      ELIGIBILITY
 

When you use the APL Platform, you represent that you meet the following primary eligibility criteria:

a.       You are at least 18 years old or accessing the APL Platform under the supervision of a parent or guardian, who in such a case will be deemed as the recipient / end-user of the Services (as defined in these Terms and Conditions) for the purpose of these Terms and Conditions.

 

b.      If your age is below that of 18 years, your parents or legal guardians can transact on behalf of you if they are registered users. You are prohibited from purchasing any material the sale or purchase of which to/by minors is prohibited and which is for consumption by adults only.

 

c.       You are legally competent to contract, and otherwise competent to receive the Services (as defined in these Terms and Conditions). Persons who are "incompetent to contract" within the meaning of the Indian Contract Act, 1872 including un-discharged insolvents etc. are not eligible to use the APL Platform.

 

d.      You have not been previously suspended or removed by APL or any other Apollo group entity or disqualified for any other reason, from availing the Services.

 

e.       APL reserves the right to terminate your membership, if any, and/or refuse to provide you with access to the APL Platform if APL discovers that you are under the age of 18 years.

 

f.        These Terms and Conditions are published in compliance of, and are governed by the provisions of Indian laws as may be amended from time to time, including but limited to:

 

i.      The Indian Contract Act, 1872;

 

ii.     The Information Technology Act, 2000 and the rules, regulations, guidelines and clarifications framed thereunder, including the Information Technology (Reasonable


 

Security Practices and Procedures and Sensitive Personal Information) Rules, 2011, and the Information Technology (Intermediaries Guidelines and Digital Media Ethics Code) Rules 2021, as amended from time to time;

 

iii.      The Drugs and Cosmetic Act, 1940, read with the Drugs and Cosmetics Rules, 1945;

 

iv.      The Drugs and Magic Remedies (Objectionable Advertisements) Act, 1954;

 

v.     The Indian Medical Council Act, 1956 read with the Indian Medical Council Rules, 1957;

vi.      Pharmacy Act, 1948; and

 

vii.     The Consumer Protection Act, 2019 and Consumer Protection (E-Commerce) Rules, 2020.

 

2.      OUR SERVICES
 

Through the APL Platform, we provide you with the following services (“Services”):

 

a.       Display, advertisement, sale and delivery of medicines including over the counter drugs, other pharmaceuticals products and certain fast moving consumer goods including cosmetics, food products, private label products and medical devices. (“Products”); and

 

b.      Any other service that is made available on the Platform from time to time. The sale and purchase of Products on the APL Platform is solely undertaken by APL and no other Apollo entity. By transacting on the APL Platform in respect of any Products [or Services], you agree to be bound by these Terms and Conditions and are entitled to enforce any and all available remedies, under contract or law, only against APL. You further agree and acknowledge that the Products being purchased by you are being sold and fulfilled only by APL.

 

3.      YOUR USE OF THE APL PLATFORM
 

3.1. By using the APL Platform, you expressly agree to be bound by the Terms and Conditions. If you do not agree with any of the Terms and Conditions, please do not use the APL Platform. Any accessing, browsing, or otherwise using the APL Platform indicates your agreement to these Terms and Conditions, and any other policies or guidelines that may be applicable on the APL Platform at the time of your access and usage of the APL Platform and which may be updated from time to time.

 

3.2. These Terms and Conditions document is an electronic record in terms of the Information Technology Act, 2000 and rules made thereunder as may be applicable, and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.

 

3.3. As an end-user and recipient of Services, when you use the APL Platform, you agree to the following conditions of use:

 

3.3.1.      Due diligence conditions:
 

a.      You are solely responsible for the medical, health and personal information you provide on the APL Platform, and you are requested to use your discretion in providing such information;

 

 

b.      You will provide accurate and complete information everywhere on the APL Platform, based on which you will receive the Services;

 

c.       You will be solely responsible for all access to and use of this APL Platform by anyone using the password and identification originally assigned to you whether or not such access to and use of this APL Platform is actually authorized by you, including without limitation, all communications and transmissions and all incurred through such access or use. You are solely responsible for protecting the security and confidentiality of the password and identification assigned to you;

 

d.      The information provided by you may be used by us for the purpose of Services including analysis, research, training and disclosure (where required) to our affiliates, group companies, vendors, agents and government authorities, etc. as stated in our Privacy Policy;

 

e.      We reserve the right to refuse service or terminate accounts at our discretion, if we believe that you have violated or are likely to violate applicable law or these Terms and Conditions; and

f.        In case, you wish to rectify and/or change any of the Information provided by you for purchasing goods or availing any of the Services from Us, you can do so by raising a request for the same and to our Grievance Officer at grievances@apollopharmacy.org. We would endeavor to rectify and/or change the information as requested by you as soon as possible.

 

3.3.2.      Scope of Services:
a.      APL sells products in various categories such as medicines, medical devices, vitamins and supplements, baby food, personal care, health foods and over the counter drugs, to end customers. APL does not sell any drugs listed in Schedule X of the Drugs and Cosmetics Act, 1940 on the APL Platform; and

 

b.      APL engages in retail sale to end customers through both offline and online channels, i.e. through its outlets / physical stores as well its APL Platform. The APL Platform will display the inventory of products available in APL stores, based on the pin code entered by you on the APL Platform.

 

3.3.3.      Prohibitions:
a.        You may view and access the content available on the APL Platform solely for the purposes of availing the Services, and only as per these Terms and Conditions. You may not reproduce, distribute, display, sell, lease, transmit, create derivative works from, translate, modify, reverse-engineer, disassemble, decompile or otherwise exploit the APL Platform or any portion of it unless expressly permitted by APL in writing;

 

b.         You may not assign, transfer, or sub-contract any of your rights or obligations under these Terms or any related order for Products to any third party, unless agreed upon in writing by APL;

 

c.         You may not make any commercial use of any of the information provided on the APL Platform;

 

d.         You may not impersonate any person or entity, or falsely state or otherwise misrepresent your identity, age or         affiliation with any person or entity;

 

e.         You may not upload any content prohibited under applicable law, and/or designated as “Prohibited Content” under Section 5 below; and

f.          You may not resell any Products purchased from APL stores or the APL Platform.

 

3.3.4.      Delivery and Charges Policy:
a.        APL endeavors to carry out deliveries during and within such time period as communicated on our APL Platform and various communication channels. Our services are offered on a best-effort basis, and as such we do not provide any guarantee of the exact delivery time, which despite all our efforts, may vary from order to order, due to certain factors including but not limited to operational disruptions owing to shortage of products and manpower, strikes, lockouts, official control measures, inevitable delays by our suppliers, rider unavailability, public holidays, product unavailability/shortage, date of delivery, time of delivery, area of delivery, distance from the hub, customer demand, traffic, sudden breakdown of delivery vehicle, weather conditions, force majeure events specified below and/or any other unforeseen reasons beyond our control;

 

b.        APL does not guarantee to deliver your order within a period of two hours and delivery within the said timeline is subject to aforesaid multiple factors, as laid out in the present Terms and Conditions, to be read in entirety;

 

c.         APL shall endeavor to deliver the order at the delivery address as provided to us while placing the order on our platform. However, any interruption or disruption caused in delivery due to any incorrect details provided to us on the APL Platform shall not be our responsibility and any resultant losses/damages caused shall be your sole responsibility and will not be attributable to us in any manner whatsoever;

 

d.        Notwithstanding your request to leave your order at your doorstep or elsewhere, such request cannot be complied with and APL shall not be responsible to deliver your order if no one is available to receive the same at the delivery address, inasmuch as it could lead to theft, tampering, spoilage, contamination etc. APL shall not be liable for non-delivery or any losses/damages arising from the same in the given case scenario and any losses/damages caused by such circumstances shall be solely borne by you;

 

e.        You shall undertake to provide accurate directions, information and authorizations to accept delivery of your order. Due to your failure to comply with the same, if the order stands undelivered, the order shall be deemed to have been delivered to you and all the risks and responsibilities in relation thereto shall pass on to you;

 

f.          As part of APL’s best endeavor to deliver all orders within the promised delivery timeline, our rider may connect with you via mobile or internet call to identify the exact location of delivery. However, in the event you do not pick up the call or the call on the given number does not get connected at the first instance, for any reason whatsoever, the promised delivery timeline shall stand no longer applicable, without prejudice to the fact that the promised time is only an approximate measure of delivery time;

 

g.        The delivery charges associated with each of your purchases will be displayed on the checkout page once you place an order on the APL Platform. Any other applicable charges will also be displayed at the time of purchase and will be payable accordingly;

 

h.        Cash on Delivery (“COD”) is a payment method by which you can pay for your ordered item(s) in cash when APL delivers the orders to you at your delivery address;

 

i.          If you do not own a credit or debit card or do not wish to pay online, rather than making any advance online payment, APL COD option gives you the flexibility to pay the complete order amount on delivery through a point-of-service terminal or through cash as the case may be;

j.          In the event you choose to pay for your order via COD mode, the riders shall have the right to refuse delivery of your order if you fail to make the complete payment at the time of delivery. In that case, APL shall not be liable for any losses or damage arising from non-delivery of the order and the same shall be your sole responsibility;

 

k.         You will be informed once the order is confirmed and when the items are shipped with an update on the approximate delivery time;

 

l.          APL makes its best efforts to ship each item in your order within the approximate delivery time intimated to you at the time of placing the order. However, in some cases, it may take longer to ship the order as we may have to procure it from some other stores or our suppliers. In the unlikely event that APL is not able to ship your order completely within 36 hours of the order, we shall cancel the remaining unshipped part of the order, and send you a communication informing you about the same. In such cases, your payment against the unshipped part of the order shall be refunded, in the manner you have made the payment, in accordance with the APL Payment, Returns, and Refund Policy;

 

m.      All applicable refunds will be processed in accordance with the APL Payments, Returns and Refunds Policy available on our APL Platform;

 

n.        Delivery time periods specified on our platform shall always be non-binding under all circumstances inasmuch as delivery is a sum total of multiple factors that can assume uncertainty at any moment for unforeseen reasons beyond our control;

 

o.        To put forth its best efforts to deliver the order effectively and within the promised timeframe, both internal and third-party entities are engaged by APL to carry out deliveries with strict Standard Operating Procedures. Please note that third-party services will be governed by their own terms of service and other policies applicable to the corresponding third party and we have no control or connection to it whatsoever and we make no representation or endorsement regarding the accuracy, relevancy, copyright compliance, legality, completeness, timeliness or quality of any product, services, advertisements and other content appearing in or linked to the services of the third party; and

 

p.        APL does not make any inter-state deliveries of medicine. Inter-state delivery of medicines is fulfilled through external delivery partners. APL may also engage external delivery partners for certain inter-city and local deliveries. Any delay, loss, harm, theft or damage arising from the shipping of products by the external delivery partner is the sole liability of the external delivery partner. APL shall not be held liable for the actions of the external delivery partner in any way whatsoever.

 

3.3.5.      International Delivery:
 

International delivery is not available currently. You can access the website to order items while being located anywhere in the world, but the shipping address has to be in India.

 

3.3.6.      Additional Information:
 

a.      APL shall have the right, at our sole discretion, to refuse or cancel any orders placed for that product, unless the product has already been dispatched; and


b.      You will compensate APL for any extra cost incurred for redelivery in the event of a non- delivery in the first instance on account of a mistake by you (i.e. wrong name or address or any other wrong information).

 

3.3.7.      Medicine Delivery Policy:
 

a.      Valid prescription from a doctor is mandatory for all medicine orders, apart from when the law permits dispatch of medicine without a prescription. You may be requested to upload a scanned copy of the prescription on the APL Platform;

 

b.      You agree that the prescription uploaded by you will be examined by a registered pharmacist where applicable or necessary under law, and your order shall be considered confirmed only after the prescription is accepted by the Pharmacist;

 

c.       You agree and consent to the particulars of your prescription will be recorded by APL in accordance with its obligations under applicable laws;

 

d.      You may be required to display the prescription, whether offline or online, for the purpose of record keeping by APL, at the time of picking up medicines or accepting delivery of medicines through an online order; and

 

e.      APL will have a right to reject (either fully or partially) your Order, in case it is found that the prescription shared by you is not as per the relevant applicable statutory requirements and same shall be informed to you through various communication channels.

 

4.      PROHIBITED CONTENT
 

a.       You shall not upload to, distribute, or otherwise publish through the APL Platform, the following Prohibited Content, which includes any content, information, or other material that:

 

b.      belongs to another person and which you do not own the rights to;

 

c.       is harmful, harassing, blasphemous, defamatory, obscene, pornographic, pedophilic, invasive of another's privacy, including bodily privacy, insulting or harassing on the basis of gender, libelous, racially or ethnically objectionable, or otherwise inconsistent with or contrary to the laws in force;

 

d.      is    hateful, racially or  ethnically objectionable, disparaging of any person;

 

e.       relates to or seems to encourage money laundering or gambling,

 

f.        harm minors in any way; infringes any patent, trademark, copyright or other proprietary rights;

 

g.      violates any law in India for the time being in force;


h.      deceives or misleads the addressee about the origin of your message and intentionally communicates any information which is patently false or misleading in nature but may reasonably be perceived as a fact;

 

i.        communicates any information which is grossly offensive or menacing in nature;

 

j.        impersonates another person;

 

k.      threatens the unity, integrity, defense, security or sovereignty of India, friendly relations with foreign states, or public order;

 

l.        is patently false and untrue, and is written or published in any form, with the intent to mislead or harass a person, entity or agency for financial gain or to cause any injury to any person;

 

m.    incites any offence or prevents investigation of any offence or insults any other nation;

 

n.      is abusive or inappropriate to the HSP conducting your medical consultation or any employees, consultants or technicians of AHEL or any other Apollo group company or affiliate who you may interact with for availing Services; and

 

o.      is not relating to the medical consultation or relating to any of the Services you avail from us.

You also understand and acknowledge that if you fail to adhere to the above, we have the right to remove such information and/or immediately terminate your access to the Services and/or to the APL Platform.

 

5.      INDEMNITY
 

a.       By using the APL Platform and/or the Service, you agree, to the fullest extent permitted by law, to indemnify and keep indemnified and hold APL, its affiliates and any Apollo group companies, and its directors, officers, employees, affiliates, agents, contractors, and licensors harmless with respect to any claims, losses, costs, charges and expenses including reasonable attorney fees that the concerned indemnified persons may suffer on account of your breach of these Terms;

 

b.      your use of the APL Platform and/or the Service;

 

c.       incorrect or inaccurate credit/debit card details provided by you;

 

d.      you using a credit/debit card which is not lawfully owned by you;

 

e.       you permitting a third party to use your password or other means to access your account;

 

f.        your non-compliance with applicable law or regulations in the jurisdiction in which you are accessing the APL Platform and/or the Service;


g.      you providing a false, forged, unauthorized or manipulated prescription; and

 

h.      any action taken by APL as part of its investigation of a suspected violation of these Terms or as a result of its finding or decision that a violation of these Terms has occurred.

 

6.      LIMITATION OF LIABILITY
 

By using our Services, you confirm that you understand and agree to the following:

 

a.       To the extent permitted by applicable law, APL or its affiliates or any Apollo group companies will not be liable to you for any special, indirect, incidental, consequential, punitive, reliance, or exemplary damages arising out of or relating to:

 

(i)           These Terms and Conditions and Privacy Policy;

 

(ii)        Your use or inability to use the APL Platform; and

 

(iii)    Your use of any third-party services you contacted through the APL Platform.

 

b.      APL does not warrant that the APL Platform or any of the Services or Products available through it will be uninterrupted or free from errors. There may be delay, omissions, interruption, and/or inaccuracies in materials or Service available through the APL Platform.

 

c.       Although APL takes reasonable steps to prevent the introduction of viruses, worms or other malicious code to the APL Platform, APL does not represent or warrant that the APL Platform, or the Service or Products or materials that may be made available through the APL Platform are free from such destructive features. APL is not liable for any damages or harm attributable to such features or arising directly or indirectly from such features.

 

d.      To the extent permitted by law, APL shall not be liable to you or to any third party for any direct, incidental, indirect, special or consequential losses, damages whatsoever (including, but not limited to, lost profits, revenue, contracts, anticipated savings, goodwill or wasted expenditure, business interruption, loss of programs or other data on your information system or any other indirect or consequential loss), even if APL has been advised, knew, or should have known of the possibility of such damages, arising out of or related                                                                            to:

 

(i)                 your use of or reliance on the APL Platform, any information, hyperlinks or content contained therein, or Services included on or otherwise made available to you through the APL Platform;

 

(ii)              your provision of information, personal or otherwise, to APL;

 

(iii)            the provision of Services by APL;

 

(iv)             acts or negligence on the part of APL, its agents or employees; and


(v)               Errors, delays or deficiencies in services or theft or damage of Products, attributable to third parties who assist APL such as delivery partners.

 

e.       To the fullest extent permitted by law, APL disclaims and excludes all warranties and representations, express, implied or statutory, with respect to the APL platform or APL’s services, or with respect to the accuracy, currency or completeness of the information provided by APL, including the implied warranties of merchantability or fitness for a particular purpose and non-infringement of a patent, trademark or other intellectual property right. The APL platform, including, without limitation, all content, information and links contained therein, is provided “as-is” without any warranty that it will be uninterrupted or error free. You expressly agree that your use of this APL platform is at your sole risk.

 

f.        Notwithstanding anything herein to the contrary, APL’s aggregate liability (whether in contract, tort or otherwise) for any loss or damage that you may incur on any account whatsoever, arising out of your use of the APL Platform, shall be limited to a sum equal to the amount paid or payable by you for the Product(s) or Services in respect of one incident or series of incidents attributable to the same cause.

 

g.      APL reserves the right to refuse Service, terminate accounts, remove or edit content, or cancel orders anytime at their sole discretion.

 

h.      No claims or action arising out of, or related to, the use of the APL Platform or these terms and conditions may be brought by you more than one (1) year after the cause of action relating to such claim or action arose.

 

i.        We have selected the Products on the basis that they will be used for personal use only. If you are planning to use them for business purposes you are advised to make sure that you are covered by a proper insurance plan. Where you decide to use the Products in the course of a business, we exclude (to the fullest extent permitted by law) those warranties and conditions relating to fitness for a particular purpose. Our maximum liability to business users arising out of or in connection with the Products shall be limited to the replacement value of the Product in question. In relation to business users, we do not accept liability for the fitness of Products for business purposes, nor do we accept liability for loss of use of the Product, nor any loss over and above the cost of the Products in the event of a claim for breach of warranty or condition.

 

This section shall survive the termination of this Agreement and the termination of your use of our Services or the APL Platform.

 

7.      DATA & INFORMATION POLICY
 

We respect your right to privacy in respect of any personal information provided to us for the purposes of availing our Services. To see how we collect and use your personal information, please see our Privacy Policy

 

8.      INTELLECTUAL PROPERTY AND OWNERSHIP
 

You recognize and agree that all copyright, registered trademarks and other intellectual property rights on all materials or contents provided as part of the APL Platform belong to us


at all times or to those who grant us the license for their use. You are permitted to use this material and/or content only as expressly authorized by our licensors or us. No use of these may be made without the prior written authorization of APL. All Product names, trade names, service names, tag lines, or logotype distinguished in form, text, or otherwise from surrounding text (e.g., all capital letters), (collectively, “Marks”) are trademarks owned by or licensed to APL, unless otherwise noted. The Marks on the APL Platform are variously protected by the laws of India. Use of any of these Marks may not be made without the prior written consent of APL, except for the sole purpose of identifying the Products or Services originating from APL. You acknowledge and agree that the material and content shown at the APL Platform is made available for your personal non-commercial use only and that you may download such material and content only for the purpose of using this APL Platform. You further acknowledge that any other use of the material and content of the APL Platform is strictly prohibited and you agree not to (and agree not to assist or facilitate any third party to) copy, reproduce, transmit, publish, display, distribute, commercially exploit or create derivative works of such material and content. The APL Platform may provide the opportunity for Registered Users to post reviews and other comments, questions, suggestions, or other information (“User Content”) on the APL Platform. You warrant that any such User Content submitted by you to the APL Platform is original (and does not infringe the copyright of others), and you hereby grant APL a perpetual, irrevocable, non-exclusive, royalty free license to use such User Content so submitted, without any further recourse to you, and you hereby waive all rights in such User Content. APL has the right but not the obligation to monitor and edit or remove any activity or User Content, and takes no responsibility and assumes no liability for any User Content posted by you or content posted by any third party.

 

9.      OTHER CONDITIONS
 

Please note that your payments are processed in accordance with applicable law and you may refer to our Payments and Refund Policy for details. By using our Services, you further confirm that you understand and agree to the following:

 

a.       That you will use the services provided by APL, its affiliates, consultants and contracted companies, for lawful purposes only and comply with all applicable laws and regulations while using the APL Platform and transacting on the APL Platform.

 

b.      You will provide true, accurate, complete and current information in all instances where such information is requested of you. APL reserves the right to confirm and validate the information and other details provided by you at any point of time. If upon confirmation your details are found not to be true (wholly or partly), APL has the right in its sole discretion to reject the registration and debar you from using the Services of APL and / or other affiliated websites without prior intimation whatsoever.

 

c.       That you using your best and prudent judgment before entering into any transaction through this APL Platform doing so at your sole risk.

 

APL reserves the right to transfer, assign or sub-contract the benefit of the whole or part of any of its rights or obligations under these Terms or any related contract, to any third party. If any part of these Terms is held by any competent authority to be invalid or unenforceable in whole or in part, the validity or enforceability of the other Terms shall not be affected. These Terms do not create or confer any rights or benefits enforceable by any person that is not a party. No


delay or failure by APL to exercise any powers, rights or remedies under these Terms will operate as a waiver of them nor will any single or partial exercise of any such powers, rights or remedies preclude any other or further exercise of them. Any waiver to be effective must be in writing and signed by an authorized representative of APL. These Terms including the documents or other sources referred to in these Terms supersede all prior representations, understandings and agreements between you and APL relating to the use of the APL Platform (including the use of Services and/or order of Products) and sets forth the entire agreement and understanding between you and APL for your use of the APL Platform. When you visit the APL Platform or send e-mail to us, you are communicating with us electronically. You consent to receive communication from us electronically. We may communicate with you by e-mail or by posting notices on the APL Platform. You agree that all agreements, notices, disclosures, and other communication that we provide to you electronically satisfy any legal requirement that such communication be in writing.

 

10.  THIRD PARTY LINKS AND RESOURCES
 

Where the APL Platform contain links to other sites and resources provided by third parties (including where our social media sharing plug-ins include links to third party sites), these links are provided for your information only/ merely as a convenience. We have no control over the contents of those websites or resources and accept no responsibility for them or for any loss or damage that may arise from your use of them. Any links to such linked Internet sites should no way be construed as an endorsement, representation or promotion by APL as to the content, representation, accuracy, products or services found or otherwise described in such linked Internet sites. Use of those linked Internet sites/links is done at your own risk and cost. You will be bound by the privacy policy and terms of use of the respective website when you navigate away from the APL Platform to any such website.

 

11.  AMENDMENTS
 

We may from time to time update or revise these Terms and Conditions. Every time you wish to use the APL Platform, please check the relevant Terms and Conditions and Privacy Policy to ensure you understand the terms that apply at that time.

 

12.  EVENTS BEYOND OUR CONTROL
 

We will not be liable for any non-compliance or delay in compliance with any of the obligations we assume under any contract including any delay or failure to deliver Products when caused by events that are beyond our reasonable control (“Force Majeure”). Force Majeure shall include any act, event, failure to exercise, omission or accident that is beyond our reasonable control, including, among others, the                            following:

 

a.       Strike, lockout or other forms of protest;

 

b.      Civil unrest, revolt, invasion, terrorist attack or terrorist threat, war (declared or not) or threat or preparation for war;

 

c.       Fire, explosion, storm, flood, earthquake, collapse, epidemic or any other natural disaster;

 

d.      Inability to use public or private transportation and telecommunication systems; and


e.       Acts, decrees, legislation, regulations or restrictions of any government or public authority including any judicial determination.

 

Our obligations deriving from any contracts should be considered suspended during the period in which Force Majeure remains in effect and we will be given an extension of the period in which to fulfil these obligations by an amount of time we shall communicate to you, not being less than the time that the situation of Force Majeure lasted.

 

13.  TERMINATION
 
a.       We reserve the right to refuse the use of Services immediately in case your conduct is deemed by us to be in contravention of applicable acts, laws, rules and regulations or these Terms and Conditions; and

 

b.      For change in law specifically, we reserve our rights to suspend our obligations under any contract indefinitely, and / or provide Services under revised Terms and Conditions.

 

14.  APPLICABLE LEGISLATION AND JURISDICTION
 

The use of our APL Platform and the contract between you and APL shall be governed by the laws applicable in India, without regard to the conflict of law rules. Any dispute relating to the use of our Services will be only resolved exclusively in the Courts at Hyderabad, India but not in any other Court.

 

15.  CONTACT US
 

If you have any comments, query or grievances regarding the Services, Terms and Conditions and   Privacy   Policy,    you    may    contact    Upendra    Dasu,    our    Grievance    Officer at grievances@apollopharmacy.org or 040-23481183. Please note that upon lodging of a complaint, a ticket number shall be given to you by which you may track the status of your complaint.''',
                        overflow: TextOverflow.fade,
                          textAlign: TextAlign.justify,
                          style: GoogleFonts.montserrat(
                            textStyle: TextStyle(
                              color: kDarkBlue3,
                              fontWeight: FontWeight.w500,
                              fontSize: h * 0.018
                            )
                          ),
                        ),
                  ),
                  SizedBox(
                    width: w * 0.03,
                  ),
                ],
              )
            ],
          ),
        ),
      ),
    );
  }
}
